### ISSUE TITLE
Pointer events prevents navigation on fixed header

### ISSUE THREAD

**Issue by yepzdk** [itk-dev/filmfolk#113]
We have some Css preventing navigation when header is fixed. Related to disabling the left side and always showing the menu.

The issue:

```css
@media (min-width: 75rem) {
    .site-header__fixable.is-fixed:not(.is-expanded) {
        pointer-events: none;
    }
}
```
